WIP

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -4,9 +4,9 @@ on:
     branches:
       - main
 
-  pull_request:
-    branches:
-      - main
+#   pull_request:
+#     branches:
+#       - main
 
 jobs:
   analyze-package:
@@ -19,13 +19,29 @@ jobs:
         uses: flutterings/dart-package-analyzer@v1
         id: pana-analysis
 
-  build:
+  check-scores:
     runs-on: ubuntu-latest
-    if: github.ref != 'refs/heads/stable'
     needs: analyze-package
+    steps:
+      - name: Check scores
+        env:
+          SCORE: ${{ needs.analyze-package.outputs.score }}
+        run: |
+          if [[ $SCORE -gt 100 ]]; then
+            echo "Score is greater than 100, proceeding to publish package."
+          else
+            echo "Score is less than or equal to 100, exiting with error."
+            exit 1
+          fi
+
+  build-and-publish:
+    runs-on: ubuntu-latest
+    needs: check-scores
+    if: steps.check-scores.outcome == 'success'
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
+
       - name: Setup Java environment
         uses: actions/setup-java@v1
         with:
@@ -48,30 +64,5 @@ jobs:
       - name: Run widget tests
         run: flutter test
 
-      - name: Publish package
+      - name: Publish package dry run
         run: flutter pub publish --dry-run
-
-      # Add your other build steps here...
-
-  check-scores:
-    runs-on: ubuntu-latest
-    if: github.ref != 'refs/heads/stable'
-    needs: analyze-package
-    steps:
-      - name: Check scores
-        env:
-          TOTAL: ${{ needs.analyze-package.outputs.total }}
-          TOTAL_MAX: ${{ needs.analyze-package.outputs.total_max }}
-        run: |
-          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
-          if (( $PERCENTAGE < 50 )); then
-            echo "Score too low!"
-            exit 1
-          fi
-
-  exit:
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/stable'
-    steps:
-      - name: Exit without action
-        run: exit 0
